<?php
/**
 * TFM HTML Sitemap — generation, caching, queries, metabox
 * Moved verbatim from topfiremedia.php during modularization — no logic change.
 */

if (!defined('ABSPATH')) {
    exit;
}

// HTML Sitemap Metabox
function tfm_sitemap_add_metabox() {
    $settings = tfm_load_settings();

    // Only add metabox if sitemap is enabled
    if (!$settings['sitemap_enabled']) {
        return;
    }

    // Get all public post types
    $post_types = get_post_types(['public' => true], 'names');

    foreach ($post_types as $post_type) {
        // Skip attachments
        if ($post_type === 'attachment') {
            continue;
        }

        add_meta_box(
            'tfm_sitemap_metabox',
            'HTML Sitemap Settings',
            'tfm_sitemap_metabox_callback',
            $post_type,
            'side',
            'default'
        );
    }
}

add_action('add_meta_boxes', 'tfm_sitemap_add_metabox');

function tfm_sitemap_save_metabox($post_id) {
    // Check if sitemap is enabled first
    $settings = tfm_load_settings();
    if (!$settings['sitemap_enabled']) {
        return;
    }

    // Check nonce
    if (!isset($_POST['tfm_sitemap_metabox_nonce']) || !wp_verify_nonce($_POST['tfm_sitemap_metabox_nonce'], 'tfm_sitemap_metabox')) {
        return;
    }

    // Check user permissions
    if (!current_user_can('edit_post', $post_id)) {
        return;
    }

    // Save or delete the meta
    if (isset($_POST['tfm_sitemap_exclude']) && $_POST['tfm_sitemap_exclude'] == '1') {
        update_post_meta($post_id, '_tfm_sitemap_exclude', '1');
    } else {
        delete_post_meta($post_id, '_tfm_sitemap_exclude');
    }
}

add_action('save_post', 'tfm_sitemap_save_metabox');

function tfm_sitemap_metabox_callback($post) {
    wp_nonce_field('tfm_sitemap_metabox', 'tfm_sitemap_metabox_nonce');

    $exclude_from_sitemap = get_post_meta($post->ID, '_tfm_sitemap_exclude', true);
    ?>
    <p>
        <label for="tfm_sitemap_exclude">
            <input type="checkbox" id="tfm_sitemap_exclude" name="tfm_sitemap_exclude" value="1" <?php checked($exclude_from_sitemap, '1'); ?>>
            Exclude from HTML Sitemap
        </label>
    </p>
    <p class="description">
        When checked, this <?php echo esc_html(get_post_type_object($post->post_type)->labels->singular_name); ?> will not appear in HTML sitemaps generated by the TFM plugin.
    </p>
    <?php
}


function tfm_sitemap_get_posts($post_type, $args = []) {
    // Default query args
    $query_args = [
        'post_type' => $post_type,
        'post_status' => 'publish',
        'posts_per_page' => -1,
        'orderby' => 'menu_order title',
        'order' => 'ASC',
        'no_found_rows' => true,
        'update_post_meta_cache' => false,
        'meta_query' => [
            [
                'key' => '_tfm_sitemap_exclude',
                'compare' => 'NOT EXISTS'
            ]
        ]
    ];

    // Allow shortcode args to override defaults
    if (isset($args['orderby'])) {
        $query_args['orderby'] = $args['orderby'];
    }
    if (isset($args['order'])) {
        $query_args['order'] = $args['order'];
    }

    $query = new WP_Query($query_args);
    return $query->posts;
}

function tfm_sitemap_get_pages_hierarchical($args = []) {
    $query_args = [
        'post_type' => 'page',
        'post_status' => 'publish',
        'posts_per_page' => -1,
        'orderby' => 'menu_order title',
        'order' => 'ASC',
        'no_found_rows' => true,
        'update_post_meta_cache' => false,
        'meta_query' => [
            [
                'key' => '_tfm_sitemap_exclude',
                'compare' => 'NOT EXISTS'
            ]
        ]
    ];

    // Allow shortcode args to override defaults
    if (isset($args['orderby'])) {
        $query_args['orderby'] = $args['orderby'];
    }
    if (isset($args['order'])) {
        $query_args['order'] = $args['order'];
    }

    $query = new WP_Query($query_args);
    return $query->posts;
}

function tfm_sitemap_get_posts_by_category($args = []) {
    $settings = tfm_load_settings();

    $categories = get_categories([
        'hide_empty' => isset($settings['sitemap_exclude_empty_cats']) ? $settings['sitemap_exclude_empty_cats'] : true
    ]);

    $result = [];

    foreach ($categories as $category) {
        $query_args = [
            'cat' => $category->term_id,
            'post_status' => 'publish',
            'posts_per_page' => -1,
            'orderby' => 'date',
            'order' => 'DESC',
            'no_found_rows' => true,
            'update_post_meta_cache' => false,
            'meta_query' => [
                [
                    'key' => '_tfm_sitemap_exclude',
                    'compare' => 'NOT EXISTS'
                ]
            ]
        ];

        // Allow shortcode args to override defaults
        if (isset($args['orderby'])) {
            $query_args['orderby'] = $args['orderby'];
        }
        if (isset($args['order'])) {
            $query_args['order'] = $args['order'];
        }

        $posts = get_posts($query_args);

        if (!empty($posts)) {
            $result[] = [
                'category' => $category,
                'posts' => $posts
            ];
        }
    }

    return $result;
}

function tfm_sitemap_format_date($date) {
    return mysql2date(get_option('date_format'), $date);
}

function tfm_sitemap_generate($args = []) {
    if (!tfm_sitemap_is_enabled()) {
        return '<p>HTML sitemap is not enabled.</p>';
    }

    $settings = tfm_load_settings();

    // Check cache first
    $cached = tfm_sitemap_get_cached($args);
    if ($cached !== false) {
        return $cached;
    }

    // Get post types to include
    $post_types = isset($args['post_types']) ? explode(',', $args['post_types']) : (isset($settings['sitemap_post_types']) ? $settings['sitemap_post_types'] : ['page', 'post']);

    // Get display options
    $show_dates = isset($args['show_dates']) ? filter_var($args['show_dates'], FILTER_VALIDATE_BOOLEAN) : (isset($settings['sitemap_show_dates']) ? $settings['sitemap_show_dates'] : true);
    $show_counts = isset($args['show_counts']) ? filter_var($args['show_counts'], FILTER_VALIDATE_BOOLEAN) : (isset($settings['sitemap_show_counts']) ? $settings['sitemap_show_counts'] : true);

    ob_start();
    ?>

    <div class="tfm-html-sitemap">
        <?php foreach ($post_types as $post_type): ?>
            <?php
            $post_type_obj = get_post_type_object($post_type);
            if (!$post_type_obj) continue;

            $section_title = $post_type_obj->labels->name;
            ?>

            <div class="tfm-sitemap-section tfm-sitemap-<?php echo esc_attr($post_type); ?>">
                <h2><?php echo esc_html($section_title); ?></h2>

                <?php if ($post_type === 'page'): ?>
                    <?php $pages = tfm_sitemap_get_pages_hierarchical($args);
                    if (!empty($pages)):
                        echo '<ul class="tfm-sitemap-pages">';
                        foreach ($pages as $page):
                            echo '<li><a href="' . esc_url(get_permalink($page->ID)) . '">' . esc_html($page->post_title) . '</a>';
                            if ($show_dates) {
                                echo ' <span class="tfm-sitemap-date">(' . esc_html(tfm_sitemap_format_date($page->post_modified)) . ')</span>';
                            }
                            echo '</li>';
                        endforeach;
                        echo '</ul>';
                    else:
                        echo '<p>No pages found.</p>';
                    endif; ?>

                <?php elseif ($post_type === 'post'): ?>
                    <?php
                    $posts_by_category = tfm_sitemap_get_posts_by_category($args);
                    if (!empty($posts_by_category)):
                    ?>
                        <?php foreach ($posts_by_category as $category_data): ?>
                            <div class="tfm-sitemap-category">
                                <h3><?php echo esc_html($category_data['category']->name); if ($show_counts): ?><span class="tfm-sitemap-count">(<?php echo count($category_data['posts']); ?>)</span><?php endif; ?></h3>
                                <ul><?php foreach ($category_data['posts'] as $post): ?>
                                    <li><a href="<?php echo esc_url(get_permalink($post->ID)); ?>"><?php echo esc_html($post->post_title); ?></a><?php if ($show_dates): ?> <span class="tfm-sitemap-date">(<?php echo esc_html(tfm_sitemap_format_date($post->post_modified)); ?>)</span><?php endif; ?></li>
                                <?php endforeach; ?>
                                </ul>
                            </div>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <p>No posts found.</p>
                    <?php endif; ?>

                <?php else: ?>
                    <?php
                    $posts = tfm_sitemap_get_posts($post_type, $args);
                    if (!empty($posts)):
                    ?>
                        <ul class="tfm-sitemap-posts"><?php foreach ($posts as $post): ?>
                            <li><a href="<?php echo esc_url(get_permalink($post->ID)); ?>"><?php echo esc_html($post->post_title); ?></a><?php if ($show_dates): ?> <span class="tfm-sitemap-date">(<?php echo esc_html(tfm_sitemap_format_date($post->post_modified)); ?>)</span><?php endif; ?></li>
                        <?php endforeach; ?>
                        </ul>
                    <?php else: ?>
                        <p>No <?php echo esc_html($section_title); ?> found.</p>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>

    <?php
    $content = ob_get_clean();

    // Remove wpautop and other content filters that could mess with the HTML
    $content = preg_replace('/<p><\/p>/', '', $content); // Remove empty paragraphs
    $content = preg_replace('/<br\s*\/?>/', '', $content); // Remove stray br tags

    // Cache the result
    tfm_sitemap_set_cached($content, $args);

    return $content;
}

// HTML Sitemap Generation Functions
function tfm_sitemap_is_enabled() {
    $settings = tfm_load_settings();
    return isset($settings['sitemap_enabled']) && $settings['sitemap_enabled'];
}

function tfm_sitemap_get_cache_key($args = []) {
    return 'tfm_sitemap_' . md5(serialize($args));
}

function tfm_sitemap_get_cached($args = []) {
    if (!tfm_sitemap_is_enabled()) {
        return false;
    }

    return get_transient(tfm_sitemap_get_cache_key($args));
}

function tfm_sitemap_set_cached($content, $args = []) {
    if (!tfm_sitemap_is_enabled()) {
        return;
    }

    $settings = tfm_load_settings();
    $cache_key = tfm_sitemap_get_cache_key($args);
    $cache_timeout = isset($settings['sitemap_cache_timeout']) ? $settings['sitemap_cache_timeout'] : 3600;

    set_transient($cache_key, $content, $cache_timeout);
}

function tfm_sitemap_clear_cache() {
    global $wpdb;

    // Clear all tfm sitemap transients
    $wpdb->query("DELETE FROM {$wpdb->options} WHERE option_name LIKE '_transient_tfm_sitemap_%'");
    $wpdb->query("DELETE FROM {$wpdb->options} WHERE option_name LIKE '_transient_timeout_tfm_sitemap_%'");
}
